const fs = require('fs');
const path = require('path');

// Portuguese (pt_PT) translations map
const translations = {
  // Plugin metadata
  "Text To Speech TTS Accessibility": "Texto Para Voz TTS Acessibilidade",
  "https://atlasaidev.com/": "https://atlasaidev.com/",
  "The most user-friendly Text-to-Speech Accessibility plugin. Just install and automatically add a Text to Audio player to your WordPress site!": "O plugin de Acessibilidade Texto-para-Voz mais fácil de usar. Basta instalar e adicionar automaticamente um leitor de Texto para Áudio ao seu site WordPress!",
  "AtlasAiDev": "AtlasAiDev",
  "http://atlasaidev.com/": "http://atlasaidev.com/",

  // Common UI
  "Plugins": "Plugins",
  "Audio Status": "Estado do Áudio",
  "TTS Status": "Estado TTS",
  "All Posts": "Todas as Publicações",
  "Audio Generated": "Áudio Gerado",
  "TTS Enabled": "TTS Ativado",
  "Audio Not Generated": "Áudio Não Gerado",
  "TTS Not Enabled": "TTS Não Ativado",
  "Post ID or User ID is missing": "Falta o ID da publicação ou o ID do utilizador",
  "This feature requires Pro version.": "Esta funcionalidade requer a versão Pro.",

  // SMTP/Email
  "WP Mail SMTP is using default PHP mail. Consider configuring an SMTP server for reliable email delivery.": "O WP Mail SMTP está a usar o PHP mail padrão. Considere configurar um servidor SMTP para entrega fiável de e-mail.",
  "Email sending may not work on localhost. Please install an SMTP plugin (like WP Mail SMTP) and configure it with a real email service (Gmail, SendGrid, Mailgun, etc.) for reliable email delivery.": "O envio de e-mail pode não funcionar em localhost. Por favor, instale um plugin SMTP (como WP Mail SMTP) e configure-o com um serviço de e-mail real (Gmail, SendGrid, Mailgun, etc.) para entrega fiável.",
  "No SMTP plugin detected. Emails will be sent using PHP mail() which may be unreliable. Consider installing WP Mail SMTP for better deliverability.": "Nenhum plugin SMTP detetado. Os e-mails serão enviados usando PHP mail() que pode ser pouco fiável. Considere instalar o WP Mail SMTP para melhor entregabilidade.",
  "Invalid settings data.": "Dados de configuração inválidos.",
  "Please provide at least one valid email address.": "Por favor, forneça pelo menos um endereço de e-mail válido.",
  "Schedule report settings saved successfully.": "Configurações do relatório agendado guardadas com sucesso.",
  "Please configure recipients first.": "Por favor, configure primeiro os destinatários.",
  "Test report sent successfully! Check your inbox.": "Relatório de teste enviado com sucesso! Verifique a sua caixa de entrada.",
  "Failed to send test report.": "Falha ao enviar relatório de teste.",
  "Error: %s": "Erro: %s",
  "No SMTP plugin is configured. Please install and configure WP Mail SMTP or a similar plugin for reliable email delivery.": "Nenhum plugin SMTP está configurado. Por favor, instale e configure o WP Mail SMTP ou um plugin semelhante para entrega fiável de e-mail.",
  "Please check your %s plugin configuration and verify your SMTP credentials are correct.": "Por favor, verifique a configuração do plugin %s e confirme que as suas credenciais SMTP estão corretas.",

  // Analytics Reports
  "[Test] %s - TTS Analytics Report": "[Teste] %s - Relatório de Análise TTS",
  "%s - TTS Analytics Report": "%s - Relatório de Análise TTS",
  "TEST REPORT": "RELATÓRIO DE TESTE",
  "TTS Analytics Report - %s": "Relatório de Análise TTS - %s",
  "Summary": "Resumo",
  "Total Plays": "Total de Reproduções",
  "Unique Listeners": "Ouvintes Únicos",
  "Completions": "Conclusões",
  "Minutes Played": "Minutos Reproduzidos",
  "Top 10 Posts": "Top 10 Publicações",
  "%d plays": "%d reproduções",
  "Device & Browser Stats": "Estatísticas de Dispositivo e Navegador",
  "Devices": "Dispositivos",
  "Browsers": "Navegadores",
  "Geographic Distribution": "Distribuição Geográfica",
  "This report was generated by Text to Audio plugin on %s": "Este relatório foi gerado pelo plugin Texto para Áudio em %s",
  "View full analytics dashboard": "Ver painel completo de análise",
  "Generated on %s": "Gerado em %s",
  "Summary Overview": "Visão Geral",
  "Initializations": "Inicializações",
  "Pauses": "Pausas",
  "Downloads": "Transferências",
  "Posts Tracked": "Publicações Rastreadas",
  "Engagement Milestones": "Marcos de Envolvimento",
  "Reached": "Alcançado",
  "Device Types": "Tipos de Dispositivo",
  "Device": "Dispositivo",
  "Count": "Contagem",
  "No data available": "Sem dados disponíveis",
  "Browser": "Navegador",
  "Operating Systems": "Sistemas Operativos",
  "OS": "SO",
  "Top Countries": "Principais Países",
  "Country": "País",
  "Top 20 Posts by Interactions": "Top 20 Publicações por Interações",
  "Post Title": "Título da Publicação",
  "Plays": "Reproduções",
  "Time (sec)": "Tempo (seg)",
  "Interactions": "Interações",
  "Generated by Text to Audio Plugin for %s": "Gerado pelo Plugin Texto para Áudio para %s",

  // API
  "You do not have permission to access this resource.": "Não tem permissão para aceder a este recurso.",
  "Invalid nonce or insufficient permissions.": "Nonce inválido ou permissões insuficientes.",
  "Invalid or missing nonce for frontend POST request.": "Nonce inválido ou em falta para pedido POST do frontend.",

  // Button labels
  "Listen": "Ouvir",
  "Pause": "Pausa",
  "Resume": "Retomar",
  "Replay": "Repetir",
  "Start": "Iniciar",
  "Stop": "Parar",
  "Save": "Guardar",

  // Aliases
  "Text to Speech Aliases": "Aliases de Texto para Voz",
  "Add New Row": "Adicionar Nova Linha",
  "Actual Text": "Texto Real",
  "To Read": "Para Ler",
  "All fields must be filled!": "Todos os campos devem ser preenchidos!",
  "Successfully Saved.": "Guardado com sucesso.",
  "More than 1 alias is available in the pro version. Please": "Mais de 1 alias está disponível na versão pro. Por favor",
  "Buy Pro version": "Comprar versão Pro",
  "Click To Know How It Works?": "Clique para saber como funciona?",

  // Notices
  "Convert unlimited characters to MP3 in bulk.": "Converta caracteres ilimitados para MP3 em massa.",
  "WPML, GTranslate, TranslatePress Plugins Support": "Suporte para plugins WPML, GTranslate, TranslatePress",
  "Works with ACF, SCF, and other popular plugins.": "Funciona com ACF, SCF e outros plugins populares.",
  "Google Cloud Text-to-Speech & ChatGPT Text-to-Speech (usage fees apply)": "Google Cloud Texto-para-Voz e ChatGPT Texto-para-Voz (taxas de utilização aplicáveis)",
  "Live integration support + 14-day money-back guarantee (conditions apply).": "Suporte de integração ao vivo + garantia de reembolso de 14 dias (condições aplicáveis).",
  "50+ languages support in pro version.": "Suporte para mais de 50 idiomas na versão pro.",
  "Download the audio file for offline listening.": "Transfira o ficheiro de áudio para ouvir offline.",
  "Improved UI and Responsive of the button.": "Interface e responsividade do botão melhoradas.",
  "Multiple Audio Player Support.": "Suporte para Múltiplos Leitores de Áudio.",
  "Customizable content selection with CSS selectors": "Seleção de conteúdo personalizável com seletores CSS",
  "Exclude content by categories, tags, IDs": "Excluir conteúdo por categorias, etiquetas, IDs",
  "Unlimited Download MP3 files": "Transferências ilimitadas de ficheiros MP3",
  "200+ Voices with Google Cloud Text To Speech": "Mais de 200 vozes com Google Cloud Texto para Voz",
  "Advance analytics & Text Aliases support.": "Análise avançada e suporte a Aliases de Texto.",

  // Analytics pro notices
  "Number of times the MP3 file downloaded. 🔒": "Número de vezes que o ficheiro MP3 foi transferido. 🔒",
  "Number of times the player reached the end. 🔒": "Número de vezes que o leitor chegou ao fim. 🔒",
  "Percentage of times the play button was clicked after initiation. 🔒": "Percentagem de vezes que o botão de reprodução foi clicado após a iniciação. 🔒",
  "Percentage of times users listened till the end. 🔒": "Percentagem de vezes que os utilizadores ouviram até ao fim. 🔒",
  "Average listening time per play. 🔒": "Tempo médio de escuta por reprodução. 🔒",
  "Average number of pauses per play. 🔒": "Número médio de pausas por reprodução. 🔒",

  // General notices
  "Text To Speech TTS": "Texto Para Voz TTS",
  "Text To Speech TTS Pro": "Texto Para Voz TTS Pro",
  "%6$s %2$s %3$s %4$s plugin is compitable with  %5$s . %7$s": "%6$s %2$s %3$s O plugin %4$s é compatível com %5$s. %7$s",
  "Buy Now": "Comprar Agora",
  "%2$s %1$s": "%2$s %1$s",
  "Unlock The Premium Features": "Desbloquear as Funcionalidades Premium",
  "%6$s %2$s %3$s %4$s": "%6$s %2$s %3$s %4$s",
  "Sea More Features": "Ver Mais Funcionalidades",
  "%6$s%2$s We are seeking contributors to help translate this plugin into %4$s. If you're interested in assisting, we'd love to hear from you! Please reach out to us %5$s, and we'll provide all the necessary guidance. %3$s Thank you for choosing %1$s.": "%6$s%2$s Estamos à procura de contribuidores para ajudar a traduzir este plugin para %4$s. Se estiver interessado em ajudar, adoraríamos ouvir de si! Por favor, contacte-nos %5$s e forneceremos toda a orientação necessária. %3$s Obrigado por escolher %1$s.",
  "Translate Here": "Traduzir Aqui",
  "AtlasVoice Text To Speech TTS": "AtlasVoice Texto Para Voz TTS",
  "Try It Now": "Experimente Agora",
  "Real World Demo": "Demonstração Real",
  "How To Use": "Como Usar",
  "Download": "Transferir",
  "Contact Us": "Contacte-nos",
  "%5$s %3$s %2$s We have spent countless hours developing this free plugin for you, and we would really appreciate it if you drop us a quick rating. Your opinion matters a lot to us.%4$s It helps us to get better. Thanks for using %1$s.": "%5$s %3$s %2$s Passámos inúmeras horas a desenvolver este plugin gratuito para si, e agradeceríamos muito se nos deixasse uma avaliação rápida. A sua opinião é muito importante para nós.%4$s Ajuda-nos a melhorar. Obrigado por usar %1$s.",
  "Review Now": "Avaliar Agora",
  "Remind Me Later": "Lembrar-me Mais Tarde",
  "Already Done!": "Já Feito!",
  "Never Ask Again": "Nunca Perguntar Novamente",
  "Get Support": "Obter Suporte",
  "Asking Feedback For Text To Speech TTS": "A Pedir Feedback para Texto Para Voz TTS",
  "%5$s %3$s %2$s We are looking your feedback to improve the product, and we would really appreciate it if you drop us a quick feedback. Your opinion matters a lot to us.%4$s It helps us to get better. Thanks for using Text To Speech.": "%5$s %3$s %2$s Estamos à procura do seu feedback para melhorar o produto, e agradeceríamos muito se nos deixasse um feedback rápido. A sua opinião é muito importante para nós.%4$s Ajuda-nos a melhorar. Obrigado por usar Texto Para Voz.",
  "Give Feedback Now": "Dar Feedback Agora",
  "Invalid Request.": "Pedido Inválido.",
  "Request Successful.": "Pedido Bem-sucedido.",
  "Something is wrong.": "Algo está errado.",

  // Main plugin
  "Settings": "Definições",
  "Docs": "Documentação",
  "Support": "Suporte",
  "Write a Review": "Escrever uma Avaliação",
  "Once Weekly": "Uma Vez por Semana",
  "Once Monthly": "Uma Vez por Mês",

  // Atlas plugins page
  "The most user-friendly Text-to-Speech accessibility plugin for WordPress. Automatically adds an audio player with no API required.": "O plugin de acessibilidade Texto-para-Voz mais fácil de usar para WordPress. Adiciona automaticamente um leitor de áudio sem necessidade de API.",
  "Unlimited text-to-speech conversion": "Conversão ilimitada de texto para voz",
  "51+ languages, 20-300+ voices": "Mais de 51 idiomas, 20-300+ vozes",
  "Customizable player design": "Design do leitor personalizável",
  "Shortcode support with flexible attributes": "Suporte a shortcode com atributos flexíveis",
  "Custom Post Type & ACF compatibility": "Compatibilidade com Tipos de Publicação Personalizados e ACF",
  "No external API required (browser SpeechSynthesis)": "Sem necessidade de API externa (SpeechSynthesis do navegador)",
  "Multilingual support (WPML, GTranslate)": "Suporte multilingue (WPML, GTranslate)",
  "Analytics & engagement tracking": "Análise e rastreamento de envolvimento",
  "Display interactive 3D models and augmented reality on your WordPress & WooCommerce site for enhanced product visualization.": "Exiba modelos 3D interativos e realidade aumentada no seu site WordPress e WooCommerce para visualização melhorada de produtos.",
  "Interactive 3D model display": "Exibição interativa de modelos 3D",
  "Augmented Reality (AR) support": "Suporte a Realidade Aumentada (RA)",
  "WordPress & WooCommerce integration": "Integração WordPress e WooCommerce",
  "Mobile-optimized viewing": "Visualização otimizada para telemóvel",
  "Customizable display options": "Opções de exibição personalizáveis",
  "Reduces return rates with realistic visualization": "Reduz taxas de devolução com visualização realista",
  "Easy product page embedding": "Incorporação fácil em páginas de produto",
  "Transform WordPress into an AI-powered control center with 70+ abilities, MCP server support, and workflow builder.": "Transforme o WordPress num centro de controlo com IA com mais de 70 capacidades, suporte a servidor MCP e construtor de fluxos de trabalho.",
  "70+ abilities across 9 modules": "Mais de 70 capacidades em 9 módulos",
  "Built-in MCP Server (JSON-RPC 2.0)": "Servidor MCP integrado (JSON-RPC 2.0)",
  "JWT authentication": "Autenticação JWT",
  "Drag-and-drop workflow builder": "Construtor de fluxos de trabalho arrastar e soltar",
  "Multi-provider AI support (OpenAI, Gemini, Claude)": "Suporte multi-fornecedor de IA (OpenAI, Gemini, Claude)",
  "WooCommerce AI Store Manager": "Gestor de Loja IA WooCommerce",
  "Post editor AI integration": "Integração de IA no editor de publicações",
  "Active": "Ativo",
  "Activate": "Ativar",
  "Learn More": "Saber Mais",
  "Features": "Funcionalidades",
  "Install Now": "Instalar Agora",
  "Installing...": "A instalar...",
  "Installation failed. Please try again.": "Instalação falhou. Por favor, tente novamente.",
  "AtlasAiDev Plugins": "Plugins AtlasAiDev",
  "Discover and install plugins by AtlasAiDev to enhance your WordPress site.": "Descubra e instale plugins da AtlasAiDev para melhorar o seu site WordPress.",

  // Blocks
  "Color Settings": "Definições de Cor",
  "Background Color": "Cor de Fundo",
  "Text Color": "Cor do Texto",
  "Button Settings": "Definições do Botão",
  "Button Width (%)": "Largura do Botão (%)",
  "Custom CSS": "CSS Personalizado",
  "class selector .tta__listen_content": "seletor de classe .tta__listen_content",
  "Text To Audio: Tap to listen post.": "Texto Para Áudio: Toque para ouvir a publicação.",
  "Text to audio customize button.": "Botão de personalização texto para áudio.",

  // Bulk MP3
  "Are you sure? You want to regenerate all MP3 files ?": "Tem a certeza? Quer regenerar todos os ficheiros MP3?",
  "All MP3 File Generated": "Todos os Ficheiros MP3 Gerados",

  // Player
  "Click to seek": "Clique para procurar",
  "Player Settings": "Definições do Leitor",
  "Close": "Fechar",
  "Language": "Idioma",
  "Voice": "Voz",
  "Speed": "Velocidade",
  "Pitch": "Tom",
  "Volume": "Volume",
  "Unmute": "Ativar som",
  "Mute": "Silenciar",

  // Multi-select
  "No IDs selected": "Nenhum ID selecionado",
  "Select IDs": "Selecionar IDs",
  "Showing button to multiple post is not supported in free version.": "Mostrar o botão em múltiplas publicações não é suportado na versão gratuita.",
  "Select Items...": "Selecionar Itens...",

  // Aliases page
  "More than 1 alias is available in the pro version. Please ": "Mais de 1 alias está disponível na versão pro. Por favor ",
  "Here a short text have to write to inform the user about this feature purpose": "Aqui deve ser escrito um breve texto para informar o utilizador sobre o propósito desta funcionalidade",
  "Write actual text": "Escrever texto real",
  "Write read aloud text": "Escrever texto para leitura em voz alta",
  "Add New": "Adicionar Novo",
  "Loading...": "A carregar...",

  // Analytics
  "CSV exported successfully!": "CSV exportado com sucesso!",
  "Error exporting CSV": "Erro ao exportar CSV",
  "PDF report opened. Use 'Save as PDF' in the print dialog.": "Relatório PDF aberto. Use 'Guardar como PDF' no diálogo de impressão.",
  "Report downloaded as HTML. Open in browser and print to save as PDF.": "Relatório transferido como HTML. Abra no navegador e imprima para guardar como PDF.",
  "Failed to generate PDF report.": "Falha ao gerar relatório PDF.",
  "Error exporting PDF": "Erro ao exportar PDF",
  "Analytics": "Análise",
  "Track and analyze your TTS player engagement to understand listener behavior.": "Rastreie e analise o envolvimento do seu leitor TTS para compreender o comportamento dos ouvintes.",
  "Analytics is Currently Disabled": "A Análise Está Atualmente Desativada",
  "Enable analytics using the toggle above to start tracking your TTS player interactions and view detailed metrics.": "Ative a análise usando o botão acima para começar a rastrear as interações do seu leitor TTS e ver métricas detalhadas.",

  // Date ranges
  "Yesterday": "Ontem",
  "Last 7 Days": "Últimos 7 Dias",
  "Last 30 Days": "Últimos 30 Dias",
  "Last 14 Days": "Últimos 14 Dias",
  "Last 90 Days": "Últimos 90 Dias",
  "All Time": "Todo o Período",
  "Custom Range": "Intervalo Personalizado",

  // Browser Analytics
  "Browser Analytics": "Análise de Navegador",
  "more": "mais",
  "Pro": "Pro",

  // Engagement Funnel
  "Init": "Início",
  "Play": "Reproduzir",
  "25%": "25%",
  "50%": "50%",
  "75%": "75%",
  "End": "Fim",
  "Engagement Funnel": "Funil de Envolvimento",
  "Play Rate:": "Taxa de Reprodução:",
  "Completion Rate:": "Taxa de Conclusão:",
  "Biggest Drop:": "Maior Queda:",
  "50% → 75%": "50% → 75%",

  // Export section
  "CSV export initiated. Check your downloads.": "Exportação CSV iniciada. Verifique as suas transferências.",
  "Export failed. Please try again.": "Exportação falhou. Por favor, tente novamente.",
  "PDF export initiated. Check your downloads.": "Exportação PDF iniciada. Verifique as suas transferências.",
  "Please enter at least one recipient email address.": "Por favor, introduza pelo menos um endereço de e-mail de destinatário.",
  "Report schedule saved successfully.": "Agendamento de relatório guardado com sucesso.",
  "Failed to save schedule settings.": "Falha ao guardar definições de agendamento.",
  "Please enter recipient email addresses first.": "Por favor, introduza primeiro os endereços de e-mail dos destinatários.",
  "Failed to send test report. Please check your network connection.": "Falha ao enviar relatório de teste. Por favor, verifique a sua ligação de rede.",
  "CSV": "CSV",
  "PDF": "PDF",
  "Schedule Report": "Agendar Relatório",
  "Schedule Email Reports": "Agendar Relatórios por E-mail",
  "Enable automated reports": "Ativar relatórios automáticos",
  "Recipients (comma separated)": "Destinatários (separados por vírgula)",
  "Frequency": "Frequência",
  "Daily": "Diário",
  "Weekly": "Semanal",
  "Monthly": "Mensal",
  "Day": "Dia",
  "Monday": "Segunda-feira",
  "Tuesday": "Terça-feira",
  "Wednesday": "Quarta-feira",
  "Thursday": "Quinta-feira",
  "Friday": "Sexta-feira",
  "Saturday": "Sábado",
  "Sunday": "Domingo",
  "Time": "Hora",
  "Include in report:": "Incluir no relatório:",
  "Summary statistics": "Estatísticas resumidas",
  "Top 10 posts": "Top 10 publicações",
  "Geographic breakdown": "Distribuição geográfica",
  "Trend chart": "Gráfico de tendência",
  "Device stats": "Estatísticas de dispositivo",
  "Next scheduled report:": "Próximo relatório agendado:",
  "Sending...": "A enviar...",
  "Send Test Report": "Enviar Relatório de Teste",
  "Saving...": "A guardar...",
  "Save Settings": "Guardar Definições",
  "Export & Reports": "Exportação e Relatórios",

  // Date picker
  "Getting more than 30 days data is pro feature. Please ": "Obter dados de mais de 30 dias é uma funcionalidade pro. Por favor ",
  "Custom date select is only available in pro version. Please ": "A seleção de data personalizada só está disponível na versão pro. Por favor ",
  "Quick Select": "Seleção Rápida",
  "From": "De",
  "To": "Até",
  "Apply": "Aplicar",

  // Listener Segments
  "New Listeners": "Novos Ouvintes",
  "Returning": "Recorrentes",
  "Listener Segments": "Segmentos de Ouvintes",
  "New:": "Novos:",
  "Returning:": "Recorrentes:",
  "New Listeners:": "Novos Ouvintes:",
  "Avg Sessions/User:": "Sessões Médias/Utilizador:",

  // Location
  "Location": "Localização",
  "Top Cities": "Principais Cidades",
  "Unlock city-level analytics": "Desbloquear análise ao nível de cidade",

  // Peak Hours
  "Mon": "Seg",
  "Tue": "Ter",
  "Wed": "Qua",
  "Thu": "Qui",
  "Fri": "Sex",
  "Sat": "Sáb",
  "Sun": "Dom",
  "Peak Listening Hours": "Horas de Pico de Escuta",
  "Low": "Baixo",
  "Peak": "Pico",
  "Insight:": "Informação:",
  "Your peak listening time is": "O seu horário de pico de escuta é",
  "Peak Hours Heatmap": "Mapa de Calor das Horas de Pico",

  // Playing Trend
  "Playing Quantity": "Quantidade de Reproduções",
  "Playing Time (min)": "Tempo de Reprodução (min)",
  "Previous Period": "Período Anterior",
  "Playing Trend Analysis": "Análise de Tendência de Reprodução",
  "Compare with Previous Period": "Comparar com Período Anterior",
  "Enable comparison with previous period": "Ativar comparação com período anterior",
  "Quantity vs Date": "Quantidade vs Data",
  "Playing Time(min)": "Tempo de Reprodução(min)",

  // Popular Posts
  "Popular Post": "Publicação Popular",
  "Rank": "Posição",
  "Total Interactions": "Total de Interações",
  "No data available yet. Start tracking posts to see analytics.": "Sem dados disponíveis ainda. Comece a rastrear publicações para ver análises.",
  "View all": "Ver tudo",
  "posts": "publicações",
  "View All Posts": "Ver Todas as Publicações",

  // Pro overlay
  "Pro Feature": "Funcionalidade Pro",
  "Upgrade to Pro to unlock this feature and get access to advanced analytics.": "Atualize para Pro para desbloquear esta funcionalidade e ter acesso a análises avançadas.",
  "Upgrade to Pro": "Atualizar para Pro",

  // Summary Cards
  "Total Posts": "Total de Publicações",
  "Total posts with TTS player": "Total de publicações com leitor TTS",
  "Player initialization count": "Contagem de inicialização do leitor",
  "Total play button clicks": "Total de cliques no botão de reprodução",
  "Time (Min)": "Tempo (Min)",
  "Total listening time": "Tempo total de escuta",
  "Total pause actions": "Total de ações de pausa",
  "Total MP3 downloads": "Total de transferências MP3",
  "Total completions": "Total de conclusões",
  "Bounce Rate": "Taxa de Rejeição",
  "Users who didn't complete the audio": "Utilizadores que não completaram o áudio",
  "TTS Player Analytics Summary": "Resumo da Análise do Leitor TTS",
  "Total Interactions:": "Total de Interações:",

  // Track Post IDs
  "Please enable analytics first.": "Por favor, ative primeiro a análise.",
  "Date Range is only available in Pro version": "O Intervalo de Datas só está disponível na versão Pro",
  "Please provide a Post ID or date range.": "Por favor, forneça um ID de publicação ou intervalo de datas.",
  "Track Post IDs": "Rastrear IDs de Publicações",
  "Tracking more than 5 post IDs is a Pro feature": "Rastrear mais de 5 IDs de publicação é uma funcionalidade Pro",
  "Post ID": "ID da Publicação",
  "Search": "Pesquisar",
  "Clear": "Limpar",
  "Showing results for:": "A mostrar resultados para:",
  "Post ID:": "ID da Publicação:",
  "From:": "De:",
  "To:": "Até:",
  "Metric": "Métrica",
  "Value": "Valor",
  "Unlock 10+ more metrics with Pro": "Desbloqueie mais de 10 métricas com o Pro",

  // Compatibility
  "Add ACF Fields To Posts": "Adicionar Campos ACF às Publicações",
  "Adding more than 1  ACF field is a pro feature": "Adicionar mais de 1 campo ACF é uma funcionalidade pro",
  "Loading": "A carregar",

  // Customize - Button
  "Before Content": "Antes do Conteúdo",
  "After Content": "Depois do Conteúdo",
  "Bottom Fixed (Pro)": "Fundo Fixo (Pro)",
  "Bottom Left (Pro)": "Fundo Esquerdo (Pro)",
  "Bottom Right (Pro)": "Fundo Direito (Pro)",
  "Bottom Center (Pro)": "Fundo Centro (Pro)",
  "Select Player": "Selecionar Leitor",
  "Select Button Position": "Selecionar Posição do Botão",
  "Select where to display the player button": "Selecione onde exibir o botão do leitor",
  "Display Player To": "Exibir Leitor Para",
  "Choose who can see the player": "Escolha quem pode ver o leitor",
  "Player display restriction to multiple user type is available in the pro version": "A restrição de exibição do leitor para múltiplos tipos de utilizador está disponível na versão pro",
  "Who Can Download MP3 File": "Quem Pode Transferir o Ficheiro MP3",
  "MP3 Generation From Post's Publish Date": "Geração de MP3 Desde a Data de Publicação",
  "Start Generating MP3 file from an specific post publish date. Select this only if you want to generate mp3 file based on date range.": "Começar a gerar ficheiro MP3 a partir de uma data específica de publicação. Selecione isto apenas se quiser gerar ficheiros MP3 com base num intervalo de datas.",
  "?": "?",
  "Generate MP3 File Date From": "Gerar Ficheiro MP3 Desde a Data",
  "MP3 Generation Till Post's Publish Date": "Geração de MP3 Até à Data de Publicação",
  "Start Generating MP3 file till an specific post publish date. Select this only if you want to generate mp3 file based on date range.": "Gerar ficheiro MP3 até uma data específica de publicação. Selecione isto apenas se quiser gerar ficheiros MP3 com base num intervalo de datas.",
  "Generate MP3 File Date To": "Gerar Ficheiro MP3 Até à Data",

  // Customization
  "Player Customization": "Personalização do Leitor",
  "Value should be between 0-100": "O valor deve estar entre 0-100",
  "This option is only available for the pro version.": "Esta opção só está disponível para a versão pro.",
  "Please fill the  field : ": "Por favor, preencha o campo: ",
  "To select this player, you must authenticate first from the Integration menu": "Para selecionar este leitor, deve autenticar-se primeiro no menu de Integração",
  "Google Cloud TTS player is only available in the pro version.": "O leitor Google Cloud TTS só está disponível na versão pro.",
  "To select this player you have to authenticate first from Integration menu": "Para selecionar este leitor tem de se autenticar primeiro no menu de Integração",
  "ChatGPT TTS player is only available in the pro version.": "O leitor ChatGPT TTS só está disponível na versão pro.",
  "ElevenLabs TTS player is only available in the pro version.": "O leitor ElevenLabs TTS só está disponível na versão pro.",
  "Default Pro player is only available in the pro version.": "O leitor Pro Padrão só está disponível na versão pro.",
  "Text To Speech plugin stores synthesized content in the uploads folder. Your uploads folder is not writable. Please make the uploads folder writable to enjoy all features of the plugin.": "O plugin Texto Para Voz armazena conteúdo sintetizado na pasta de uploads. A sua pasta de uploads não tem permissão de escrita. Por favor, torne a pasta de uploads gravável para desfrutar de todas as funcionalidades do plugin.",
  "Customization saved.": "Personalização guardada.",
  "Now go to the \\\"Listening\\\" menu to select proper language and voice.": "Agora vá ao menu \\\"Escuta\\\" para selecionar o idioma e a voz adequados.",
  "Default": "Padrão",
  "Default Pro": "Pro Padrão",
  "Customization": "Personalização",
  "Customize the player & design to match your brand and preferences.": "Personalize o leitor e o design para combinar com a sua marca e preferências.",
  "Write here something and click listen button": "Escreva algo aqui e clique no botão ouvir",
  " Enter your text here and click the listen button to hear it spoken aloud.": " Introduza o seu texto aqui e clique no botão ouvir para o ouvir em voz alta.",
  "Watch Tutorial": "Ver Tutorial",
  "Write here something and click listen button.": "Escreva algo aqui e clique no botão ouvir.",
  "Text To Audio:  Tap to listen post.": "Texto Para Áudio: Toque para ouvir a publicação.",
  "Design Customization": "Personalização do Design",
  "Short Code | Attributes value must be wrapped with double quotation ( \\\" )": "Shortcode | Os valores dos atributos devem ser envolvidos com aspas duplas ( \\\" )",
  "tta_play_btn_shortcode": "tta_play_btn_shortcode",
  "Copied ShortCode": "Shortcode Copiado",
  "Copy Shortcode": "Copiar Shortcode",

  // Design
  "Choose player background color": "Escolha a cor de fundo do leitor",
  "Choose your color": "Escolha a sua cor",
  "Hover BG Color": "Cor de Fundo ao Passar",
  "Choose your hover background color": "Escolha a cor de fundo ao passar o rato",
  "Hover Text Color": "Cor do Texto ao Passar",
  "Choose your hover text color": "Escolha a cor do texto ao passar o rato",
  "Margin Size (Px)": "Tamanho da Margem (Px)",
  "Top": "Topo",
  "Margin Top": "Margem Superior",
  "Bottom": "Fundo",
  "Margin Bottom": "Margem Inferior",
  "Left": "Esquerda",
  "Margin Left": "Margem Esquerda",
  "Right": "Direita",
  "Margin Right": "Margem Direita",
  "Button Style": "Estilo do Botão",
  "Height": "Altura",
  "Button Height": "Altura do Botão",
  "Border": "Borda",
  "Button Border": "Borda do Botão",
  "Border Color": "Cor da Borda",
  "Font Size": "Tamanho da Fonte",
  "Radius": "Raio",
  "Border Radius": "Raio da Borda",
  "Button Properties": "Propriedades do Botão",
  "Width": "Largura",
  "Button Width": "Largura do Botão",
  "Enter Custom CSS here": "Introduza CSS personalizado aqui",

  // Docs/FAQ
  "1. Browser support issues on Android and desktop": "1. Problemas de suporte de navegador no Android e desktop",
  "This plugin is built using the browser SpeechSynthesis API. No external API is used.": "Este plugin é construído usando a API SpeechSynthesis do navegador. Nenhuma API externa é utilizada.",
  "View SpeechSynthesis documentation": "Ver documentação do SpeechSynthesis",
  "Browser and device support varies, so available voices and languages may differ between desktop and mobile devices.": "O suporte de navegador e dispositivo varia, por isso as vozes e idiomas disponíveis podem diferir entre dispositivos desktop e móveis.",
  "Submit a support ticket": "Enviar um pedido de suporte",
  "There are no browser limitations in the Pro version.": "Não existem limitações de navegador na versão Pro.",
  "2. Different voices or languages on mobile": "2. Vozes ou idiomas diferentes no telemóvel",
  "SpeechSynthesis support varies between browsers and devices. Some voices may be available on desktop but not on mobile.": "O suporte SpeechSynthesis varia entre navegadores e dispositivos. Algumas vozes podem estar disponíveis no desktop mas não no telemóvel.",
  "The Pro version does not have these limitations.": "A versão Pro não tem estas limitações.",
  "3. Can I exclude certain words from playback?": "3. Posso excluir certas palavras da reprodução?",
  "Yes. You can exclude specific words or phrases in the Pro version.": "Sim. Pode excluir palavras ou frases específicas na versão Pro.",
  "Use the pipe (|) symbol to separate multiple words or phrases.": "Use o símbolo pipe (|) para separar múltiplas palavras ou frases.",
  "4. Can I exclude specific HTML tags from playback?": "4. Posso excluir tags HTML específicas da reprodução?",
  "The Pro version allows excluding content wrapped in specific HTML tags.": "A versão Pro permite excluir conteúdo envolvido em tags HTML específicas.",
  "Use the pipe (|) symbol to exclude multiple tags.": "Use o símbolo pipe (|) para excluir múltiplas tags.",
  "5. How can I change button text?": "5. Como posso alterar o texto do botão?",
  "Button text can be changed using shortcode attributes or filters. Filters always override shortcode values.": "O texto do botão pode ser alterado usando atributos de shortcode ou filtros. Os filtros substituem sempre os valores do shortcode.",
  "6. How do I add a custom CSS class to the button?": "6. Como adiciono uma classe CSS personalizada ao botão?",
  "7. Backend filters (Free version)": "7. Filtros de backend (versão Gratuita)",
  "Filter": "Filtro",
  "Arguments": "Argumentos",

  // Integrations - ChatGPT
  "ChatGPT TTS feature is only in pro version.": "A funcionalidade ChatGPT TTS só está disponível na versão pro.",
  "ChatGPT text to speech feature is only in pro version.": "A funcionalidade texto para voz ChatGPT só está disponível na versão pro.",
  "Text To Speech plugin store's synthesized content into uploads folder. Your uploads folder is not writable. Please make uploads folder writable to enjoy the whole features of the plugin.": "O plugin Texto Para Voz armazena conteúdo sintetizado na pasta de uploads. A sua pasta de uploads não tem permissão de escrita. Por favor, torne a pasta de uploads gravável para desfrutar de todas as funcionalidades do plugin.",
  "API key is saved successfully": "Chave API guardada com sucesso",
  "Something went wrong": "Algo correu mal",
  "Set ChatGPT API key": "Definir chave API ChatGPT",
  "paste here chatgpt_tts_api_key": "cole aqui chatgpt_tts_api_key",
  "Submit": "Enviar",
  "How to get chatGPT API key?": "Como obter a chave API do ChatGPT?",
  "Click here": "Clique aqui",

  // Integrations - ElevenLabs
  "ElevenLabs TTS feature is only in pro version.": "A funcionalidade ElevenLabs TTS só está disponível na versão pro.",
  "ElevenLabs text to speech feature is only in pro version.": "A funcionalidade texto para voz ElevenLabs só está disponível na versão pro.",
  "Set ElevenLabs API key": "Definir chave API ElevenLabs",
  "paste here elevenlabs_api_key": "cole aqui elevenlabs_api_key",
  "How to get ElevenLabs API key?": "Como obter a chave API da ElevenLabs?",

  // Integrations - Google Cloud TTS
  "Backup MP3 Files To Google Cloud Storage Can Be Enabled If Google Text To Speech Is Authenticated.": "O Backup de Ficheiros MP3 para Google Cloud Storage pode ser ativado se o Google Texto para Voz estiver autenticado.",
  "This is not a service account file. The \\\"type\\\" field must be \\\"service_account\\\". You may have downloaded the wrong file type.": "Este não é um ficheiro de conta de serviço. O campo \\\"type\\\" deve ser \\\"service_account\\\". Pode ter transferido o tipo de ficheiro errado.",
  "Invalid service account file. Missing required fields: %s": "Ficheiro de conta de serviço inválido. Campos obrigatórios em falta: %s",
  "The uploaded file is not valid JSON. Please make sure you downloaded the correct service account key file.": "O ficheiro carregado não é JSON válido. Por favor, certifique-se de que transferiu o ficheiro de chave de conta de serviço correto.",
  "Could not read the file. Please try again.": "Não foi possível ler o ficheiro. Por favor, tente novamente.",
  "Google cloud text to speech feature is only in pro version.": "A funcionalidade Google Cloud texto para voz só está disponível na versão pro.",
  "Please create a valid bucket name first": "Por favor, crie primeiro um nome de bucket válido",
  "Settings saved successfully.": "Definições guardadas com sucesso.",
  "Please select a service account JSON file first.": "Por favor, selecione primeiro um ficheiro JSON de conta de serviço.",
  "File uploaded successfully. You can now test the connection below.": "Ficheiro carregado com sucesso. Agora pode testar a ligação abaixo.",
  "You are already authenticated": "Já está autenticado",
  "You have to be authenticated to revoke.": "Tem de estar autenticado para revogar.",
  "Do you want to revoke access and delete the file uploaded during authentication. If you delete the file you have to upload the file again. Make sure you have a backup otherwise, you have to crete another auth file from Google Cloud text to speech.": "Quer revogar o acesso e eliminar o ficheiro carregado durante a autenticação? Se eliminar o ficheiro, terá de o carregar novamente. Certifique-se de que tem uma cópia de segurança, caso contrário terá de criar outro ficheiro de autenticação no Google Cloud texto para voz.",
  "Authentication removed.": "Autenticação removida.",
  "Network error. Please try again.": "Erro de rede. Por favor, tente novamente.",
  "BCMath extension is not enabled. Please enable this extension. Learn more how to enable.": "A extensão BCMath não está ativada. Por favor, ative esta extensão. Saiba mais sobre como ativar.",
  "This bucket is already have to your cloud storage.": "Este bucket já existe no seu armazenamento na nuvem.",
  "Are you sure you want to create a bucket named \\\"%1$s\\\"? You already have a bucket named \\\"%2$s\\\". If you create a new bucket, all MP3 files will be generated again. Please decide carefully.": "Tem a certeza de que quer criar um bucket chamado \\\"%1$s\\\"? Já tem um bucket chamado \\\"%2$s\\\". Se criar um novo bucket, todos os ficheiros MP3 serão gerados novamente. Por favor, decida com cuidado.",
  "BCMath Extension Missing": "Extensão BCMath em Falta",
  "The BCMath PHP extension is required for Google Cloud TTS. ": "A extensão PHP BCMath é necessária para o Google Cloud TTS. ",
  "Learn how to enable it": "Saiba como ativá-la",
  "Uploads Folder Not Writable": "Pasta de Uploads Sem Permissão de Escrita",
  "The uploads folder must be writable to store generated audio files. Please check your server file permissions.": "A pasta de uploads deve ter permissão de escrita para armazenar ficheiros de áudio gerados. Por favor, verifique as permissões de ficheiro do seu servidor.",
  "Setup Guide": "Guia de Configuração",
  "Hide": "Ocultar",
  "Show": "Mostrar",
  "Go to": "Ir para",
  "Google Cloud Console": "Consola Google Cloud",
  "and create a project (or select an existing one).": "e crie um projeto (ou selecione um existente).",
  "Enable the": "Ative o",
  "Cloud Text-to-Speech API": "API Cloud Texto-para-Voz",
  "Optional, for Cloud Storage backup": "Opcional, para backup no Cloud Storage",
  "Cloud Storage API": "API Cloud Storage",
  "IAM & Admin > Service Accounts": "IAM e Admin > Contas de Serviço",
  "and create a new service account.": "e crie uma nova conta de serviço.",
  "Assign roles:": "Atribuir funções:",
  "Cloud Text-to-Speech User": "Utilizador Cloud Texto-para-Voz",
  "(required)": "(obrigatório)",
  "Storage Admin": "Admin de Armazenamento",
  "only if using Cloud Storage backup": "apenas se usar backup Cloud Storage",
  "Click on the service account > \\\"Keys\\\" tab > \\\"Add Key\\\" > \\\"Create new key\\\" > select \\\"JSON\\\".": "Clique na conta de serviço > separador \\\"Chaves\\\" > \\\"Adicionar Chave\\\" > \\\"Criar nova chave\\\" > selecione \\\"JSON\\\".",
  "Upload the downloaded JSON file below.": "Carregue o ficheiro JSON transferido abaixo.",
  "Video Tutorial": "Tutorial em Vídeo",
  "Learn How To Integrate Google Text To Speech With AtlasVoice Pro Plugin?": "Saiba Como Integrar o Google Texto Para Voz com o Plugin AtlasVoice Pro?",
  "Authentication": "Autenticação",
  "Click here to Upload": "Clique aqui para Carregar",
  "Upload service account JSON file": "Carregar ficheiro JSON de conta de serviço",
  "Service Account:": "Conta de Serviço:",
  "Project:": "Projeto:",
  "IAM Console": "Consola IAM",
  "Connection Test": "Teste de Ligação",
  "Verify that your service account can connect to Google Cloud Text-to-Speech API.": "Verifique se a sua conta de serviço consegue ligar-se à API Google Cloud Texto-para-Voz.",
  "Testing...": "A testar...",
  "Test TTS Connection": "Testar Ligação TTS",
  "Storage Configuration": "Configuração de Armazenamento",
  "Store MP3 Files To Google Cloud Storage": "Armazenar Ficheiros MP3 no Google Cloud Storage",
  "Click To Know How To Enable Automatic Store To Google Cloud Storage": "Clique Para Saber Como Ativar o Armazenamento Automático no Google Cloud Storage",
  "Automatically sync generated audio files in cloud storage for store & easy access.": "Sincronize automaticamente ficheiros de áudio gerados no armazenamento na nuvem para guardar e aceder facilmente.",
  "Required:": "Obrigatório:",
  "Your service account needs the \\\"Storage Admin\\\" role to use Cloud Storage.": "A sua conta de serviço precisa da função \\\"Admin de Armazenamento\\\" para usar o Cloud Storage.",
  "Assign it to": "Atribua-a a",
  "in": "em",
  "Open IAM Console": "Abrir Consola IAM",
  "Test Storage Access": "Testar Acesso ao Armazenamento",
  "Google Cloud Storage Bucket Name": "Nome do Bucket Google Cloud Storage",
  "Click Here To Know Bucket Name Rules": "Clique Aqui Para Saber as Regras de Nome do Bucket",
  "Create": "Criar",
  "Remove Authentication": "Remover Autenticação",

  // Integration main
  "Integration Setup": "Configuração de Integração",
  "AtlasVoice Pro works fully fine even without Google TTS/ChatGPT integration.": "O AtlasVoice Pro funciona perfeitamente mesmo sem integração Google TTS/ChatGPT.",
  "Select Text To Speech Service": "Selecionar Serviço de Texto para Voz",
  "-- Select a service --": "-- Selecionar um serviço --",
  "Google Cloud TTS": "Google Cloud TTS",
  "ChatGPT TTS": "ChatGPT TTS",
  "ElevenLabs TTS": "ElevenLabs TTS",
  "ElevenLabs Usage": "Utilização ElevenLabs",
  "characters": "caracteres",
  "Plan:": "Plano:",
  "Resets:": "Reinicia em:",
  "View detailed usage and billing at": "Ver utilização detalhada e faturação em",
  "OpenAI TTS Usage": "Utilização OpenAI TTS",
  "Google Cloud TTS Usage": "Utilização Google Cloud TTS",

  // Listening
  "Listening settings saved. Now all setup done. Enjoy": "Definições de escuta guardadas. Configuração completa. Desfrute",
  "Listening Preferences": "Preferências de Escuta",
  "Set your listening preferences with different voices and languages.": "Defina as suas preferências de escuta com diferentes vozes e idiomas.",
  "Voice Language": "Idioma da Voz",
  "Default Listening Language": "Idioma de Escuta Padrão",
  "Voice to speak": "Voz para falar",
  "Default Listening Voice": "Voz de Escuta Padrão",
  "Voice Speed": "Velocidade da Voz",
  "Voice Volume": "Volume da Voz",
  "Voice Pitch": "Tom da Voz",
  "Default Listening Pitch": "Tom de Escuta Padrão",
  "Your browser does not support the audio element.": "O seu navegador não suporta o elemento de áudio.",
  "Voice Model": "Modelo de Voz",
  "Default Listening Model": "Modelo de Escuta Padrão",
  "TTS-1": "TTS-1",
  "TTS-1 HD": "TTS-1 HD",
  "Model": "Modelo",
  "Multilingual v2": "Multilingue v2",
  "Turbo v2.5": "Turbo v2.5",
  "Flash v2.5": "Flash v2.5",
  "Eleven v3": "Eleven v3",
  "Output Format": "Formato de Saída",
  "MP3 44100Hz 128kbps (Default)": "MP3 44100Hz 128kbps (Padrão)",
  "MP3 44100Hz 192kbps": "MP3 44100Hz 192kbps",
  "MP3 44100Hz 96kbps": "MP3 44100Hz 96kbps",
  "MP3 44100Hz 64kbps": "MP3 44100Hz 64kbps",
  "MP3 22050Hz 32kbps": "MP3 22050Hz 32kbps",
  "Stability": "Estabilidade",
  "More variable": "Mais variável",
  "More stable": "Mais estável",
  "Similarity Boost": "Impulso de Semelhança",
  "High": "Alto",
  "Style Exaggeration": "Exagero de Estilo",
  "None": "Nenhum",
  "Exaggerated": "Exagerado",
  "Speaker Boost": "Impulso de Voz",
  "Language mapping for WPML, GTranslate plugin is available in the pro version.": "O mapeamento de idiomas para os plugins WPML, GTranslate está disponível na versão pro.",
  "Select Language For{\\\" \\\"}": "Selecionar Idioma Para{\\\" \\\"}",
  "Select Voice For{\\\" \\\"}": "Selecionar Voz Para{\\\" \\\"}",
  "Current Player Voice": "Voz Atual do Leitor",

  // Recording
  "Recording Data Saved": "Dados de Gravação Guardados",

  // Settings
  "All cache deleted": "Toda a cache eliminada",
  "Successfully Saved. Now go to the \\\"Customization\\\" menu.": "Guardado com sucesso. Agora vá ao menu \\\"Personalização\\\".",
  "Help information about this setting": "Informação de ajuda sobre esta definição",
  "Configure Settings": "Configurar Definições",
  "Configure text-to-speech player behavior and content selection": "Configure o comportamento do leitor texto-para-voz e a seleção de conteúdo",
  "Add Button or Player Automatically": "Adicionar Botão ou Leitor Automaticamente",
  "The \\\"Add Button or Player Automatically\\\" feature in a Text-to-Speech (TTS) plugin allows the plugin to automatically insert a play button or audio player into your posts or pages — without needing any manual setup.": "A funcionalidade \\\"Adicionar Botão ou Leitor Automaticamente\\\" num plugin Texto-para-Voz (TTS) permite ao plugin inserir automaticamente um botão de reprodução ou leitor de áudio nas suas publicações ou páginas — sem necessidade de configuração manual.",
  "Continue Reading After Switching To Another Tab": "Continuar a Ler Após Mudar para Outro Separador",
  "When enabled, text-to-speech will continue playing even if you navigate away from the current tab": "Quando ativado, o texto-para-voz continuará a reproduzir mesmo que navegue para fora do separador atual",
  "Stop Auto Play After Switching To TTS Tab": "Parar Reprodução Automática Após Voltar ao Separador TTS",
  "Automatically pause playback when switching back to the TTS tab from another tab": "Pausar automaticamente a reprodução ao voltar ao separador TTS a partir de outro separador",
  "When Scroll Down Stop Floating Player": "Ao Descer Parar o Leitor Flutuante",
  "Automatically pause the floating player when users scroll down the page": "Pausar automaticamente o leitor flutuante quando os utilizadores descem na página",
  "Apply number format": "Aplicar formato numérico",
  "Convert numbers to spoken words (e.g., '123' becomes 'one hundred twenty-three')": "Converter números em palavras faladas (ex.: '123' torna-se 'cento e vinte e três')",
  "Read Content From Dom": "Ler Conteúdo do DOM",
  "Use Old Player UI": "Usar Interface Antiga do Leitor",
  "Add Post Title To Read": "Adicionar Título da Publicação para Ler",
  "Include the post title in the audio playback before reading the main content": "Incluir o título da publicação na reprodução de áudio antes de ler o conteúdo principal",
  "Add Post Excerpt To Read": "Adicionar Excerto da Publicação para Ler",
  "Include the post excerpt/summary in the audio playback before reading the main content": "Incluir o excerto/resumo da publicação na reprodução de áudio antes de ler o conteúdo principal",
  "Enable TTS Status": "Ativar Estado TTS",
  "Enable TTS Status In Post Page.": "Ativar Estado TTS na Página da Publicação.",
  "Add Text Before Content(intro)": "Adicionar Texto Antes do Conteúdo (introdução)",
  "Custom text that will be read aloud before the main content begins": "Texto personalizado que será lido em voz alta antes do conteúdo principal começar",
  "Add Text Before Content": "Adicionar Texto Antes do Conteúdo",
  "Add Text After Content(outro)": "Adicionar Texto Depois do Conteúdo (conclusão)",
  "Custom text that will be read aloud after the main content finishes": "Texto personalizado que será lido em voz alta depois do conteúdo principal terminar",
  "Add Text After Content": "Adicionar Texto Depois do Conteúdo",
  "Allow Listening For Post Type": "Permitir Escuta para Tipo de Publicação",
  "Allow Listening For Post Status": "Permitir Escuta para Estado da Publicação",
  "On Free Version You Can Select Only 1 post type.": "Na Versão Gratuita pode selecionar apenas 1 tipo de publicação.",
  "Include Content By CSS Selectors": "Incluir Conteúdo por Seletores CSS",
  "Include Content By CSS Selectors feature is available in pro version": "A funcionalidade Incluir Conteúdo por Seletores CSS está disponível na versão pro",
  "Multiple selector will be multiline.": "Múltiplos seletores serão em várias linhas.",
  "Some content may be missing, It can be found by css selectors": "Algum conteúdo pode estar em falta, pode ser encontrado por seletores CSS",
  "Exclude Content By CSS Selectors": "Excluir Conteúdo por Seletores CSS",
  "Exclude Content By CSS Selectors feature is available in pro version": "A funcionalidade Excluir Conteúdo por Seletores CSS está disponível na versão pro",
  "Exclude content by CSS selectors": "Excluir conteúdo por seletores CSS",
  "You can add \\\".atlasvoice_no_read\\\" class to exclude content.": "Pode adicionar a classe \\\".atlasvoice_no_read\\\" para excluir conteúdo.",
  "Exclude HTML Tags To Speak": "Excluir Tags HTML para Falar",
  "Exclude Tags. So that its content skipped. Like ( Subscript, Superscript etc.) This is a pro feature.": "Excluir Tags. Para que o seu conteúdo seja saltado. Como (Subscript, Superscript, etc.) Esta é uma funcionalidade pro.",
  "Multiple Tags Will Be Pipe(|) Separated.": "Múltiplas Tags serão separadas por Pipe(|).",
  "Exclude tags is a pro feature.": "Excluir tags é uma funcionalidade pro.",
  "Exclude Texts To Speak": "Excluir Textos para Falar",
  "Excluding texts to be spoken is a pro feature.": "Excluir textos a serem falados é uma funcionalidade pro.",
  "Multiple Texts Will Be Pipe(|) Separated.": "Múltiplos Textos serão separados por Pipe(|).",
  "Exclude texts is a pro feature.": "Excluir textos é uma funcionalidade pro.",
  "Exclude Posts By IDs To Speak": "Excluir Publicações por IDs para Falar",
  "Exclude more than 5 IDs is a pro feature": "Excluir mais de 5 IDs é uma funcionalidade pro",
  "Multiple IDs Will Be Comma(,) Separated.": "Múltiplos IDs serão separados por Vírgula(,).",
  "Excluding more than 5 IDs is a pro feature. Multiple IDs Will Be Comma(,) Separated.": "Excluir mais de 5 IDs é uma funcionalidade pro. Múltiplos IDs serão separados por Vírgula(,).",
  "Exclude Categories To Speak": "Excluir Categorias para Falar",
  "Exclude more than 1 categories is a pro feature": "Excluir mais de 1 categoria é uma funcionalidade pro",
  "On Free Version You Can Select Only 1 Category.": "Na Versão Gratuita pode selecionar apenas 1 Categoria.",
  "Exclude Tags To Speak": "Excluir Etiquetas para Falar",
  "Exclude more than 1 tags is a pro feature": "Excluir mais de 1 etiqueta é uma funcionalidade pro",
  "On Free Version You Can Select Only 1 Tag.": "Na Versão Gratuita pode selecionar apenas 1 Etiqueta.",
  "Enable Button Icon": "Ativar Ícone do Botão",
  "Clear all cache": "Limpar toda a cache",
  "Save All": "Guardar Tudo",

  // CSS Selectors
  "Please save the post then try to add custom CSS selectors.": "Por favor, guarde a publicação e depois tente adicionar seletores CSS personalizados.",
  "Empty value can not be saved. You can uncheck the \\\"Use Own CSS Selectors\\\" Option.": "Valor vazio não pode ser guardado. Pode desmarcar a opção \\\"Usar Seletores CSS Próprios\\\".",
  "Settings Data Saved": "Dados das Definições Guardados",
  "Use Own CSS Selectors": "Usar Seletores CSS Próprios",
  "Exclude Tags. So that its content skiped. Like ( Subscript, Superscript etc.) This is a pro feature.": "Excluir Tags. Para que o seu conteúdo seja saltado. Como (Subscript, Superscript, etc.) Esta é uma funcionalidade pro.",

  // Misc strings that might have been missed with escaped quotes
  "Now go to the \"Listening\" menu to select proper language and voice.": "Agora vá ao menu \"Escuta\" para selecionar o idioma e a voz adequados.",
  "Short Code | Attributes value must be wrapped with double quotation ( \" )": "Shortcode | Os valores dos atributos devem ser envolvidos com aspas duplas ( \" )",
  "Successfully Saved. Now go to the \"Customization\" menu.": "Guardado com sucesso. Agora vá ao menu \"Personalização\".",
  "The \"Add Button or Player Automatically\" feature in a Text-to-Speech (TTS) plugin allows the plugin to automatically insert a play button or audio player into your posts or pages — without needing any manual setup.": "A funcionalidade \"Adicionar Botão ou Leitor Automaticamente\" num plugin Texto-para-Voz (TTS) permite ao plugin inserir automaticamente um botão de reprodução ou leitor de áudio nas suas publicações ou páginas — sem necessidade de configuração manual.",
  "You can add \".atlasvoice_no_read\" class to exclude content.": "Pode adicionar a classe \".atlasvoice_no_read\" para excluir conteúdo.",
  "Empty value can not be saved. You can uncheck the \"Use Own CSS Selectors\" Option.": "Valor vazio não pode ser guardado. Pode desmarcar a opção \"Usar Seletores CSS Próprios\".",
  "This is not a service account file. The \"type\" field must be \"service_account\". You may have downloaded the wrong file type.": "Este não é um ficheiro de conta de serviço. O campo \"type\" deve ser \"service_account\". Pode ter transferido o tipo de ficheiro errado.",
  "Your service account needs the \"Storage Admin\" role to use Cloud Storage.": "A sua conta de serviço precisa da função \"Admin de Armazenamento\" para usar o Cloud Storage.",
  "Click on the service account > \"Keys\" tab > \"Add Key\" > \"Create new key\" > select \"JSON\".": "Clique na conta de serviço > separador \"Chaves\" > \"Adicionar Chave\" > \"Criar nova chave\" > selecione \"JSON\".",
  "Are you sure you want to create a bucket named \"%1$s\"? You already have a bucket named \"%2$s\". If you create a new bucket, all MP3 files will be generated again. Please decide carefully.": "Tem a certeza de que quer criar um bucket chamado \"%1$s\"? Já tem um bucket chamado \"%2$s\". Se criar um novo bucket, todos os ficheiros MP3 serão gerados novamente. Por favor, decida com cuidado.",
  "Select Language For{\" \"}": "Selecionar Idioma Para{\" \"}",
  "Select Voice For{\" \"}": "Selecionar Voz Para{\" \"}",
};

// Read the .pot file
const potContent = fs.readFileSync(path.join(__dirname, '../languages/text-to-audio.pot'), 'utf8');

// Replace header
let poContent = potContent
  .replace('# Copyright (C) 2026 AtlasAiDev', '# Translation of Text To Speech TTS Accessibility into Portuguese (Portugal)')
  .replace('"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"', '"Last-Translator: AtlasAiDev <support@atlasaidev.com>\\n"')
  .replace('"Language-Team: LANGUAGE <LL@li.org>\\n"', '"Language-Team: Portuguese (Portugal) <support@atlasaidev.com>\\n"')
  .replace('"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"', '"PO-Revision-Date: 2026-03-10 12:00+0000\\n"');

// Add Language header after Content-Transfer-Encoding
poContent = poContent.replace(
  '"Content-Transfer-Encoding: 8bit\\n"',
  '"Content-Transfer-Encoding: 8bit\\n"\n"Language: pt_PT\\n"\n"Plural-Forms: nplurals=2; plural=(n != 1);\\n"'
);

// Replace each msgstr "" with translation
let translated = 0;
let total = 0;

// Process line by line for accurate matching
const lines = poContent.split('\n');
const outputLines = [];
let currentMsgid = '';
let collectingMsgid = false;

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];

  // Detect msgid line
  if (line.startsWith('msgid "') && !line.startsWith('msgid ""')) {
    currentMsgid = line.replace(/^msgid "/, '').replace(/"$/, '');
    collectingMsgid = false;
    outputLines.push(line);
    continue;
  }

  // Handle multiline msgid (continuation)
  if (collectingMsgid && line.startsWith('"')) {
    currentMsgid += line.replace(/^"/, '').replace(/"$/, '');
    outputLines.push(line);
    continue;
  }

  // Detect empty msgid (header)
  if (line === 'msgid ""') {
    currentMsgid = '';
    collectingMsgid = true;
    outputLines.push(line);
    continue;
  }

  // Detect msgstr line
  if (line === 'msgstr ""' && currentMsgid) {
    total++;
    const translation = translations[currentMsgid];
    if (translation !== undefined) {
      outputLines.push(`msgstr "${translation}"`);
      translated++;
    } else {
      outputLines.push(line);
    }
    currentMsgid = '';
    collectingMsgid = false;
    continue;
  }

  collectingMsgid = false;
  outputLines.push(line);
}

const outputPath = path.join(__dirname, '../languages/text-to-audio-pt_PT.po');
fs.writeFileSync(outputPath, outputLines.join('\n'), 'utf8');

console.log(`Translated: ${translated}/${total} strings`);
console.log(`Output: ${outputPath}`);
