/**
 * TTS-314: languages AtlasVoice TTS (player 3) can speak, code => name.
 *
 * One canonical list, generated from the AtlasVoice service (GET /v1/voices,
 * engine gtts). Regenerate it when the service adds a language.
 */
export const GTTS_LANGUAGES = {
    "af": "Afrikaans",
    "am": "Amharic",
    "sw": "Swahili",
    "ar": "Arabic",
    "hy": "Armenian",
    "eu": "Basque",
    "ca": "Catalan",
    "gl": "Galician",
    "zh": "Chinese",
    "zh-cn": "Chinese (Mandarin/China)",
    "zh-tw": "Chinese (Mandarin/Taiwan)",
    "zh-yue": "Chinese (Cantonese)",
    "yue-hant-hk": "Chinese Cantonese (Hong Kong)",
    "nl": "Dutch",
    "en": "English",
    "en-au": "English (Australia)",
    "en-in": "English (India)",
    "en-ng": "English (Nigeria)",
    "en-uk": "English (United Kingdom)",
    "en-us": "English (United States)",
    "fr": "French",
    "fr-ca": "French (Canada)",
    "de": "German",
    "el": "Greek",
    "he": "Hebrew",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "ms": "Malay",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "la": "Latin",
    "mk": "Macedonian",
    "pt": "Portuguese",
    "pt-br": "Portuguese (Brazil)",
    "pt-pt": "Portuguese (Portugal)",
    "ro": "Romanian",
    "ru": "Russian",
    "da": "Danish",
    "fi": "Finnish",
    "no": "Norwegian",
    "sv": "Swedish",
    "bg": "Bulgarian",
    "bg-bg": "Bulgarian (Bulgaria)",
    "bs": "Bosnian",
    "hr": "Croatian",
    "cs": "Czech",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "pl": "Polish",
    "sr": "Serbian",
    "sk": "Slovak",
    "uk": "Ukrainian",
    "bn": "Bengali",
    "gu": "Gujarati",
    "hi": "Hindi",
    "kn": "Kannada",
    "ml": "Malayalam",
    "mr": "Marathi",
    "ne": "Nepali",
    "pa": "Punjabi",
    "si": "Sinhala",
    "ta": "Tamil",
    "te": "Telugu",
    "ur": "Urdu",
    "fil-ph": "Filipino (Philippines)",
    "jv": "Javanese",
    "km": "Khmer",
    "my": "Burmese",
    "su": "Sundanese",
    "es": "Spanish",
    "es-ar": "Spanish (Argentina)",
    "es-es": "Spanish (Spain)",
    "es-us": "Spanish (United States)",
    "th": "Thai",
    "tr": "Turkish",
    "vi": "Vietnamese",
    "cy": "Welsh",
    "et": "Estonian",
    "sq": "Albanian",
};
